admin:
    pattern: /admin/
    defaults: { _controller: cmf_sandbox.admin:indexAction }

admin_no_slash:
    pattern: /admin
    defaults: { _controller: cmf_sandbox.admin:indexAction }

admin_create:
    pattern: /admin/create
    defaults: { _controller: cmf_sandbox.admin:createAction }
